project:
  type: website

website:
  #title: "Home"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: people.qmd
        text: People
      - href: contact.qmd
        text: Contact
        
format:
  html:
    
    # remove white space from the sides
    grid:
      sidebar-width: 0px
      body-width: 1700px
      margin-width: 0px
      #gutter-width: 0.1rem
    
    theme: cosmo
    #theme: flatly
    css: styles.css
    toc: true
    
    include-after-body: footer.html

editor: visual

